* kaisa-optimal-build
small tool uses the [[https://docs.rs/microlp/latest/microlp/][microlp]] crate to find the cheapest [[https://wiki.leagueoflegends.com/en-us/Kai'Sa][Kai'sa]] build that is above the required threshold to upgrade her abilities.
Kai'sa is a League of Legends character, who's passive ability is that she can evolve her normal abilities after she gains enough stats from items.
for her Q, it's 100 attack damage (ad), for her W it's ability power (ap), and for her E it's attack speed.
these requirements change by level, and this tool applies the level 1 stat requirements.

** acquiring =item.json=
run the following, changing =14.24.1= for whatever the most recent patch is:
#+begin_src bash
curl https://ddragon.leagueoflegends.com/cdn/14.24.1/data/en_US/item.json > item.json
#+end_src
this will download all item information, straight from riot's [[https://developer.riotgames.com/docs/lol#data-dragon][data dragon]]
** running
requires [[https://www.rust-lang.org/][rust]] and [[https://github.com/rust-lang/cargo][cargo]] installed on your machine.
then run
#+begin_src
cargo run --release
#+end_src

this will run for a bit, then output something like the following

#+begin_src
Found 116 items that contribute to desired stats
Found solution in 8.57ms
-----
Best build
Total cost: 8300

count  name                     cost   ad  ap  attack speed movement speed
1      B. F. Sword              1300   40  0   0            0
1      Amplifying Tome          400    0   20  0            0
3      Hearthbound Axe          1200   20  0   20           0
1      Nashor's Tooth           3000   0   80  50           0
-----
total                           8300   60  100 70           0
#+end_src
